<a href="https://colab.research.google.com/github/DhruvParashar673/ZineML/blob/main/ML1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [14]:
x=[1,2,3]
y=[4,5,6]
z=[223,45,6]
c=[x,y,z]
import numpy as np
v=np.array(c)
print(type(v))
print(c)
print(v)
print(v.shape)

<class 'numpy.ndarray'>
[[1, 2, 3], [4, 5, 6], [223, 45, 6]]
[[  1   2   3]
 [  4   5   6]
 [223  45   6]]
(3, 3)


In [17]:
data1 = {'Name':['Jai', 'Princi', 'Gaurav', 'Anuj'],
 'Age':[27, 47, 23 , 63],
 'Percentage':[99, 87, 85,76],
 'Address':['Lucknow', 'Kanpur', 'Allahabad','Kannauj'] }
# print(type(data1))


<class 'dict'>


In [18]:
d= np.array([[1,2,3,4,5], [10,20,30,40,50], [100,200,300,400,500],[11,2,3,4,5], [110,20,30,40,50], [1100,200,300,400,500],[111,2,3,4,5], [1560,20,30,40,50], [76100,200,300,400,500]])
print(d)

[[    1     2     3     4     5]
 [   10    20    30    40    50]
 [  100   200   300   400   500]
 [   11     2     3     4     5]
 [  110    20    30    40    50]
 [ 1100   200   300   400   500]
 [  111     2     3     4     5]
 [ 1560    20    30    40    50]
 [76100   200   300   400   500]]


In [28]:
import numpy as np
import pandas as pd
data2 = {'Name':['Jai', 'Princi', 'Gaurav', 'Anuj'],
 'Age':[27, np.nan, 23 , np.nan],
 'Percentage':[np.nan, 87, 85,76],
 'Address':['Lucknow', 'Kanpur', 'Allahabad','Kannauj']}
d=pd.DataFrame(data2)
print(d)
l=d['Age'].isnull()
l

     Name   Age  Percentage    Address
0     Jai  27.0         NaN    Lucknow
1  Princi   NaN        87.0     Kanpur
2  Gaurav  23.0        85.0  Allahabad
3    Anuj   NaN        76.0    Kannauj


0    False
1     True
2    False
3     True
Name: Age, dtype: bool

In [29]:
d.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype  
---  ------      --------------  -----  
 0   Name        4 non-null      object 
 1   Age         2 non-null      float64
 2   Percentage  3 non-null      float64
 3   Address     4 non-null      object 
dtypes: float64(2), object(2)
memory usage: 256.0+ bytes


In [30]:
d

Name   Age  Percentage    Address
0     Jai  27.0         NaN    Lucknow
1  Princi   NaN        87.0     Kanpur
2  Gaurav  23.0        85.0  Allahabad
3    Anuj   NaN        76.0    Kannauj

In [31]:
l=d[d['Age'].isnull()]
l

Name  Age  Percentage  Address
1  Princi  NaN        87.0   Kanpur
3    Anuj  NaN        76.0  Kannauj

In [32]:
age_mean=np.mean(d['Age'])
age_mean

25.0

In [34]:
l=d[d['Percentage'].isnull()]
l

Name   Age  Percentage  Address
0  Jai  27.0         NaN  Lucknow

In [36]:
x=d.iloc[:,:].values
x

array([['Jai', 27.0, nan, 'Lucknow'],
       ['Princi', nan, 87.0, 'Kanpur'],
       ['Gaurav', 23.0, 85.0, 'Allahabad'],
       ['Anuj', nan, 76.0, 'Kannauj']], dtype=object)